config/routes.rb
Rails.application.routes.draw do

  # get 'profiles/home'
  get 'profiles/home', to: 'profiles#home'
  # get 'profiles/information'
  get 'home', to: 'pages#home'
  get 'services/index'
  get 'info/meet_us'

  namespace :admin do

    resources :appointments
    resources :doctors
    resources :beds
    resources :doctor_specialties
    resources :medical_resume
    resources :nurses
    resources :patients
    resources :resumes
    resources :specialties
    resources :statuses
    resources :surgeries
    resources :users

    root to: "appointments#index"
    end

  get 'profiles/home'
  get 'profiles/information'
  get 'services/index'
  get 'info/meet_us'



  devise_for :users

  # Nueva ruta
    resources :profiles

  # Rutas protegidas por Devise para autenticación



  # http://127.0.0.1:3000/patients/patient_id/bed

  # homepage
  root to: "pages#home"

  # para services
  get 'services', to: 'services#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :nurses

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.avif", alt: "Logo", class: "logo" %>
      <span class="navbar-text ms-2">HospiCare360</span>
    <% end %>
    <button class="navbar-toggler" type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 center-links">
        <% if user_signed_in? %>
          <li class="nav-item text">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Services", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About us", info_meet_us_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.type == "Patient" %>
              <%= image_tag "https://res.cloudinary.com/dhaafwmtf/image/upload/v1726760794/avatarpat_vbudyq.png", class: "avatar", alt: "User avatar" %>
            <% else  %>
              <%= image_tag "https://res.cloudinary.com/dhaafwmtf/image/upload/v1726760721/avatar_c5eegw.png", class: "avatar", alt: "User avatar" %>
             <% end  %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.type == "Patient" %>
                <li><%= link_to "Profile", profiles_home_path, class: "dropdown-item" %></li>
              <% else %>
                <li><%= link_to "Dashboard", admin_doctors_path, class: "dropdown-item" %></li>
              <% end %>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
            </ul>
          </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
  </li>
<% end %>

      </ul>
    </div>
  </div>
</div>