config/routes.rb
Rails.application.routes.draw do

  # get 'profiles/home'
  get 'profiles/home', to: 'profiles#home'
  # get 'profiles/information'
  get 'home', to: 'pages#home'
  get 'services/index'
  get 'info/meet_us'

  namespace :admin do

    resources :appointments
    resources :doctors
    resources :beds
    resources :doctor_specialties
    resources :medical_resume
    resources :nurses
    resources :patients
    resources :resumes
    resources :specialties
    resources :statuses
    resources :surgeries
    resources :users

    root to: "appointments#index"
    end

  get 'profiles/home'
  get 'profiles/information'
  get 'services/index'
  get 'info/meet_us'



  devise_for :users

  # Nueva ruta
    resources :profiles

  # Rutas protegidas por Devise para autenticación



  # http://127.0.0.1:3000/patients/patient_id/bed

  # homepage
  root to: "pages#home"

  # para services
  get 'services', to: 'services#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :nurses

end

app/controllers/admin/nurses_controller.rb
module Admin
  class NursesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/nurses_controller.rb
class NursesController < ApplicationController
  before_action :set_nurse, only: %i[show edit update destroy]
  # Método de listado de las enfermeras
  def index
    @nurses = Nurse.all
  end

  # Métodos para mostrar detalles de la enfermera
  def show
  end

  # Para crear, hacer una nueva instancia del modelo
  def new
    @nurse = Nurse.new
  end

  # GET - Para edición
  def edit
  end

  # POST para recibir los parámetros de un formulario y guardar en la bd
  def create
    @nurse = Nurse.new(nurse_params)
    if @nurse.save
      redirect_to nurse_url(@nurse), notice: "Nurse was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH - tomar un registro existente y actualizarlo
  def update
    if @nurse.update(nurse_params)
      redirect_to nurse_url(@nurse), notice: "Nurse was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE para eliminar
  def destroy
    @nurse.destroy!
    redirect_to nurses_url, notice: 'Nurse was succesfully destroyed'
  end

  private

  def set_nurse
    @nurse = Nurse.find(params[:id])
  end

  def nurse_params
    params.require(:nurse).permit(:first_name, :last_name)
  end
end

app/views/nurses/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @nurse do |f| %>
        <% if @nurse.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @nurse.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :first_name, "Nombres" %>
          <%= f.text_field :first_name, class: "form-control", placeholder: 'Ingrese los nombres' %>
        </div>
         <div class="form-group">
          <%= f.label :last_name, "Apellidos" %>
          <%= f.text_field :last_name, class: "form-control", placeholder: 'Ingrese los apellidos' %>
        </div>
        <div class="form-group">
          <%= f.submit "Enviar", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/nurses/edit.html.erb
<h1>Editing nurse</h1>

<%= render "form", nurse: @nurse %>

<br>

<div>
  <%= link_to "Show this nurse", @nurse, class: 'btn btn-primary' %> |
  <%= link_to "Back to nurse", nurses_path, class: 'btn btn-warning' %>
</div>

app/views/nurses/index.html.erb
<h1>Listado de enfermeras</h1>
<a href="<%= new_nurse_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear enfermera</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombres</th>
      <th>Apeliidos</th>
  </thead>
  <tbody>
    <% @nurses.each do |nurse| %>
    <tr>
      <td><%= nurse.id %></td>
      <td><%= nurse.first_name %></td>
      <td><%= nurse.last_name %></td>
      <td><%= link_to "Detalles", nurse_path(nurse), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/nurses/new.html.erb
<h1>Crear nueva enfermera</h1>
<%= link_to "Regresar al listado de enfermeras", nurses_path, class: 'btn btn-primary'%>
<%= render 'form', nurse: @nurse %>

app/views/nurses/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles de la enfermera</h1>
    <%= link_to "Regresar al listado de enfermeras", nurses_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_nurse_path(@nurse), class: 'btn btn-primary' %>
    <%= button_to "Destroy this nurse", @doctor, method: :delete, class: "btn btn-danger" %>
    <%# <%= link_to "Delete this nurse", @nurse, method: :delete, class: "btn btn-danger" %>

    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombres:</b></td>
          <td><%= @nurse.first_name %></td>
        </tr>
        <tr>
          <td><b>Apellidos:</b></td>
          <td><%= @nurse.last_name %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @nurse.created_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>