config/routes.rb
Rails.application.routes.draw do

  # get 'profiles/home'
  get 'profiles/home', to: 'profiles#home'
  # get 'profiles/information'
  get 'home', to: 'pages#home'
  get 'services/index'
  get 'info/meet_us'

  namespace :admin do

    resources :appointments
    resources :doctors
    resources :beds
    resources :doctor_specialties
    resources :medical_resume
    resources :nurses
    resources :patients
    resources :resumes
    resources :specialties
    resources :statuses
    resources :surgeries
    resources :users

    root to: "appointments#index"
    end

  get 'profiles/home'
  get 'profiles/information'
  get 'services/index'
  get 'info/meet_us'



  devise_for :users

  # Nueva ruta
    resources :profiles

  # Rutas protegidas por Devise para autenticación



  # http://127.0.0.1:3000/patients/patient_id/bed

  # homepage
  root to: "pages#home"

  # para services
  get 'services', to: 'services#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :nurses

end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :patient,
             class_name: 'Patient',
             foreign_key: 'patient_id'
end

app/controllers/admin/beds_controller.rb
module Admin
  class BedsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: %i[show edit update destroy]

  def index
    @beds = Bed.all
  end

  def show
    @bed = Bed.find(params[:id])
  end

  def new
    @bed = Bed.new
  end

  def create
    @bed = Bed.new(bed_params)

    if @bed.save
      redirect_to @bed, notice: 'Bed was successfully created.'
    else
      render :new
    end
  end

  def edit
    @bed = Bed.find(params[:id])
  end

  def update
    if @bed.update(bed_params)
      redirect_to @bed, notice: 'Bed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bed.destroy
    redirect_to beds_url, notice: 'Bed was successfully destroyed.'
  end

  private

  def set_bed
    @bed = Bed.find(params[:id])
  end

  def bed_params
    params.require(:bed).permit(:created_at, :updated_at, :patient_id)
  end
end

app/views/beds/edit.html.erb
<h1>Edit Bed</h1>

<%= form_with(model: @bed, local: true) do |form| %>
  <% if @bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% @bed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.number_field :patient_id %>
  </div>

  <div class="actions">
    <%= form.submit "Update Bed" %>
  </div>
<% end %>

<%= link_to 'Back', beds_path %>

app/views/beds/index.html.erb
<h1>Beds</h1>
<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @beds.each do |bed| %>
      <tr>
        <td><%= bed.created_at %></td>
        <td><%= bed.updated_at %></td>
        <td>
          <%= link_to 'Show', bed %>
          <%= link_to 'Edit', edit_bed_path(bed) %>
          <%= link_to 'Destroy', bed, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Bed', new_bed_path %>

app/views/beds/new.html.erb
<h1><%= action_name == 'new' ? 'New Bed' : 'Edit Bed' %></h1>

<%= form_with(model: @bed) do |form| %>
  <% if @bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bed.errors.count, "error") %> prohibited this bed from being saved:</h2>
      <ul>
        <% @bed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div>
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', beds_path %>

app/views/beds/show.html.erb
<h1>Bed Details</h1>
<p>
  <strong>Created at:</strong>
  <%= @bed.created_at %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= @bed.updated_at %>
</p>

<%= link_to 'Edit', edit_bed_path(@bed) %> |
<%= link_to 'Back', beds_path %>